version: "3"
services:

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=test

  mongo-client:
    image: mongo:4
    restart: on-failure
    command: mongo --host mongo -u mongoadmin -p secret --eval "load(\"/mongo/createUser.js\")"
    volumes:
      - "./mongo:/mongo"